In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score
from scipy.spatial.distance import cdist

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/covtype_train.csv")

In [ ]:
df.head(10)

id         Elevation  ... Soil_Type Wilderness
0   0    elevation_high  ...        32          2
1   1  elevation_medium  ...         9          3
2   2    elevation_high  ...        21          2
3   3    elevation_high  ...         3          2
4   4  elevation_medium  ...        25          2
5   5    elevation_high  ...        31          2
6   6    elevation_high  ...        28          0
7   7     elevation_low  ...         0          3
8   8  elevation_medium  ...         2          2
9   9    elevation_high  ...        31          2

[10 rows x 11 columns]

In [ ]:
df.shape

(174304, 11)

In [ ]:
df.describe()

id  ...     Wilderness
count  174304.000000  ...  174304.000000
mean    87151.500000  ...       1.113956
std     50317.374998  ...       1.061284
min         0.000000  ...       0.000000
25%     43575.750000  ...       0.000000
50%     87151.500000  ...       1.000000
75%    130727.250000  ...       2.000000
max    174303.000000  ...       3.000000

[8 rows x 5 columns]

In [ ]:
df.corr()

id  ...  Wilderness
id                                1.000000  ...   -0.003116
Horizontal_Distance_To_Hydrology -0.002435  ...    0.057764
Vertical_Distance_To_Hydrology   -0.002838  ...    0.163374
Soil_Type                         0.004874  ...   -0.272381
Wilderness                       -0.003116  ...    1.000000

[5 rows x 5 columns]

In [ ]:
df.columns

Index(['id', 'Elevation', 'Aspect', 'Slope', 'Hillshade_9am', 'Hillshade_Noon',
       'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology',
       'Horizontal_Distance_To_Fire_Points', 'Soil_Type', 'Wilderness'],
      dtype='object')

In [ ]:
df.Elevation.unique()

array(['elevation_high', 'elevation_medium', 'elevation_low',
       'elevation_ultra'], dtype=object)

In [ ]:
df['Elevation'] = df['Elevation'].replace("elevation_low", 0)

In [ ]:
df.Elevation.unique()

array(['elevation_high', 'elevation_medium', 0, 'elevation_ultra'],
      dtype=object)

In [ ]:
df['Elevation'] = df['Elevation'].replace("elevation_medium", 1)
df['Elevation'] = df['Elevation'].replace("elevation_high", 2)
df['Elevation'] = df['Elevation'].replace("elevation_ultra", 3)

In [ ]:
df.Elevation.unique()

array([2, 1, 0, 3])

In [ ]:
df['Aspect'].unique()

array(['aspect_low', 'aspect_ultra', 'aspect_high', 'aspect_medium'],
      dtype=object)

In [ ]:
df['Aspect'] = df['Aspect'].replace("aspect_low", 0)

In [ ]:
df['Aspect'].unique()

array([0, 'aspect_ultra', 'aspect_high', 'aspect_medium'], dtype=object)

In [ ]:
df['Aspect'] = df['Aspect'].replace("aspect_medium", 1)
df['Aspect'] = df['Aspect'].replace("aspect_high", 2)
df['Aspect'] = df['Aspect'].replace("aspect_ultra", 3)

In [ ]:
df.Aspect.unique()

array([0, 3, 2, 1])

In [ ]:
df.Slope.unique()

array(['slope_low', 'slope_medium', 'slope_high', 'slope_ultra'],
      dtype=object)

In [ ]:
df['Slope'] = df['Slope'].replace("slope_low", 0)
df['Slope'] = df['Slope'].replace("slope_medium", 1)
df['Slope'] = df['Slope'].replace("slope_high", 2)
df['Slope'] = df['Slope'].replace("slope_ultra", 3)

In [ ]:
df.Slope.unique()

array([0, 1, 2, 3])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174304 entries, 0 to 174303
Data columns (total 11 columns):
 #   Column                              Non-Null Count   Dtype 
---  ------                              --------------   ----- 
 0   id                                  174304 non-null  int64 
 1   Elevation                           174304 non-null  int64 
 2   Aspect                              174304 non-null  int64 
 3   Slope                               174304 non-null  int64 
 4   Hillshade_9am                       174304 non-null  object
 5   Hillshade_Noon                      174304 non-null  object
 6   Horizontal_Distance_To_Hydrology    174304 non-null  int64 
 7   Vertical_Distance_To_Hydrology      174304 non-null  int64 
 8   Horizontal_Distance_To_Fire_Points  174304 non-null  object
 9   Soil_Type                           174304 non-null  int64 
 10  Wilderness                          174304 non-null  int64 
dtypes: int64(8), object(3)
memory usage: 14

In [ ]:
df.head()

id  Elevation  ...  Soil_Type  Wilderness
0   0          2  ...         32           2
1   1          1  ...          9           3
2   2          2  ...         21           2
3   3          2  ...          3           2
4   4          1  ...         25           2

[5 rows x 11 columns]

In [ ]:
df.Hillshade_9am.unique()
K=3

In [ ]:
df['Hillshade_9am'] = df['Hillshade_9am'].replace("hillshade_9am_min", 0)
df['Hillshade_9am'] = df['Hillshade_9am'].replace("hillshade_9am_max", 1)

In [ ]:
df.Hillshade_9am.unique()

array([1, 0])

In [ ]:
df.Hillshade_Noon.unique()

array(['hillnoon_max', 'hillnoon_min'], dtype=object)

In [ ]:
df['Hillshade_Noon'] = df['Hillshade_Noon'].replace("hillnoon_min", 0)
df['Hillshade_Noon'] = df['Hillshade_Noon'].replace("hillnoon_max", 1)

In [ ]:
df.Hillshade_Noon.unique()

array([1, 0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174304 entries, 0 to 174303
Data columns (total 11 columns):
 #   Column                              Non-Null Count   Dtype 
---  ------                              --------------   ----- 
 0   id                                  174304 non-null  int64 
 1   Elevation                           174304 non-null  int64 
 2   Aspect                              174304 non-null  int64 
 3   Slope                               174304 non-null  int64 
 4   Hillshade_9am                       174304 non-null  int64 
 5   Hillshade_Noon                      174304 non-null  int64 
 6   Horizontal_Distance_To_Hydrology    174304 non-null  int64 
 7   Vertical_Distance_To_Hydrology      174304 non-null  int64 
 8   Horizontal_Distance_To_Fire_Points  174304 non-null  object
 9   Soil_Type                           174304 non-null  int64 
 10  Wilderness                          174304 non-null  int64 
dtypes: int64(10), object(1)
memory usage: 1

In [ ]:
df.Horizontal_Distance_To_Fire_Points.unique()

array(['low', 'mid', 'high'], dtype=object)

In [ ]:
df['Horizontal_Distance_To_Fire_Points'] = df['Horizontal_Distance_To_Fire_Points'].replace("low", 0)
df['Horizontal_Distance_To_Fire_Points'] = df['Horizontal_Distance_To_Fire_Points'].replace("mid", 1)
df['Horizontal_Distance_To_Fire_Points'] = df['Horizontal_Distance_To_Fire_Points'].replace("high", 2)

In [ ]:
df['Horizontal_Distance_To_Fire_Points'].unique()

array([0, 1, 2])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174304 entries, 0 to 174303
Data columns (total 11 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   id                                  174304 non-null  int64
 1   Elevation                           174304 non-null  int64
 2   Aspect                              174304 non-null  int64
 3   Slope                               174304 non-null  int64
 4   Hillshade_9am                       174304 non-null  int64
 5   Hillshade_Noon                      174304 non-null  int64
 6   Horizontal_Distance_To_Hydrology    174304 non-null  int64
 7   Vertical_Distance_To_Hydrology      174304 non-null  int64
 8   Horizontal_Distance_To_Fire_Points  174304 non-null  int64
 9   Soil_Type                           174304 non-null  int64
 10  Wilderness                          174304 non-null  int64
dtypes: int64(11)
memory usage: 14.6 MB


Now we've converted all our dataset into numerical.

In [ ]:
# #Now doing k means
# from sklearn.cluster import KMeans

# km = KMeans( n_clusters=3, init='random', n_init=10, max_iter=300,  tol=1e-04, random_state=0 )

# y_km = km.fit_predict(X)

In [ ]:
df.head()


id  Elevation  ...  Soil_Type  Wilderness
0   0          2  ...         32           2
1   1          1  ...          9           3
2   2          2  ...         21           2
3   3          2  ...          3           2
4   4          1  ...         25           2

[5 rows x 11 columns]

In [ ]:
de=df

In [ ]:
de = de.sample(frac =.25)

In [ ]:
de

id  Elevation  ...  Soil_Type  Wilderness
114614  114614          1  ...         28           0
71762    71762          2  ...         29           0
155120  155120          1  ...         29           0
145277  145277          1  ...         10           2
63728    63728          2  ...         38           2
...        ...        ...  ...        ...         ...
16078    16078          3  ...         38           0
133197  133197          1  ...          9           2
147946  147946          2  ...         30           2
50127    50127          2  ...         28           0
89931    89931          0  ...          9           3

[43576 rows x 11 columns]

In [ ]:
dr=df

In [ ]:
dr.drop(['target'], axis=1) # drop target as we need to compare with target only at the end of our prediction

In [ ]:
dx=dr.sample(frac=0.25)

In [ ]:
from sklearn.cluster import KMeans, AgglomerativeClustering

In [ ]:
import sklearn.metrics as sm

In [ ]:
y_true = de['target']

KeyError: ignored

In [ ]:
yy_true = df['target']

In [ ]:
# Reference from https://github.com/PacktWorkshops/The-Unsupervised-Learning-Workshop/blob/master/Chapter01/Exercise1.06/Exercise1.06.ipynb
def predict(X, k):
    dv = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/covtype_train.csv")
    dv.dropna(inplace = True)
    # lists for creating the labels and centroids for the future use
    centroids_history = list()
    labels_history = list()
    dd=np.random.choice
    cc=centroids_history.append
    rand_index = dd(X.shape[0], K)  
    centroids = X[rand_index]
    cc(centroids)
    while True:
#Here we will be predicting for the values in each cluster according to the eucledian distance which we are calculating here
        labels = np.argmin(cdist(X, centroids), axis=1)
        labels_history.append(labels)
        new_centroids = np.array([X[labels == i].mean(axis=0)
                                for i in range(K)])
        cc(new_centroids)
        if np.all(centroids == new_centroids):
            break
        centroids = new_centroids
    
    return centroids, labels, centroids_history, labels_history
# Checking for the centroid obatined previosuly and now     

In [ ]:
X_mat = dx.values

In [ ]:
#np.random.seed(0)
centroids, labels, centroids_history, labels_history = predict(X_mat, 7)

In [ ]:
import joblib

In [ ]:
filename = '/content/drive/MyDrive/Colab Notebooks/finalized_model.sav'
joblib.dump(labels, filename)

In [ ]:
ddd=loaded_model = joblib.load(filename)
foo = np.array(ddd)
m = np.median(foo[foo > 0])
foo[foo == 0] = int(m)

In [ ]:
sdd=sm.accuracy_score(y_true.to_numpy(), foo) * 100
print("accuracy = ")
print(sdd)

In [ ]:
X_maat = df.values

In [ ]:
#np.random.seed(0)
centroids, labelss, centroids_history, labels_history = predict(X_maat, 7)

In [ ]:
from sklearn.preprocessing import StandardScaler, normalize
normalized_df = normalize(df) 

In [ ]:
normalized_df = pd.DataFrame(normalized_df) 

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2) 
pcadf = pca.fit_transform(normalized_df) 
import joblib
filename = '/content/drive/MyDrive/Colab Notebooks/gaussian.sav'
joblib.dump(pcadf, filename)
hhhh=loaded_model = joblib.load(filename)
hhhh = pd.DataFrame(pcadf) 
hhhh.columns = ['Component 1', 'Component 2']#2Cluster2', 'Cluster3','Cluster4','Cluster5','Cluster6','Cluster7'] 
hhhh

In [ ]:
fig, ax = plt.subplots(figsize=(12, 8))
scatter = ax.scatter(hhhh['Component 1'],hhhh['Component 2'], alpha=0.5)
plt.title('Plot Gaussian', fontsize = 20)
plt.xlabel('Component 1', fontsize = 15)
plt.ylabel('Component 2', fontsize = 15)
ax.plot([])
ax.grid()
plt.show()

In [ ]:
pca.explained_variance_ratio_